
version: 2

models:
  - name: stg_airports
    description: Staged airports data from source
    meta:
      model_maturity: in dev
    columns:
      - name: airport_id
        tests:
          - dbt_expectations.expect_column_to_exist
          - unique
          - not_null

  - name: stg_plane
    description: Staged planes data from source
    meta:
      model_maturity: in dev
    columns:
      - name: plane_id
        tests:
          - dbt_expectations.expect_column_to_exist
          - unique
          - not_null  

  - name: stg_flights_2008
    description: Staged flights data from source
    meta:
      model_maturity: in dev
    columns:
      - name: flight_id
        tests:
          - dbt_expectations.expect_column_to_exist
          - unique
          - not_null

