version: 2

sources:
  - name: openflight_database
    description: Database is created for demo purpose.
    database: analytics
    schema: raw
    tables:
      - name: airlines
        desciption: Table contains IATA code of each airline in the USA and its associated name. 
        columns:
          - name: iata_code
            description: IATA stands for International Air Transport Association. Two different airlines can have the same IATA code.
            tests: 
              - not_null
      - name: airports
        description: Table contains location details of airports in the USA
        columns:
          - name: iata_code
            description: Airport code standardized by the International Air Transport Association (IATA)
            tests:
              - not_null
      - name: customers
        description: Table contains data of passengers, including their demographic details and travel history
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - first_name
                - birth_date
                - address_line_1
      - name: plane
        description: Table contains technical specifications of active airplanes, such as manufacturer, model, engine type, etc. 
        tests:
          - expect_multiple_cols_not_null:
              list_column_names: 
                - manufacturer
                - model
                - engine_type
        columns:
          - name: type
            tests:
            - accepted_values:
                values: ['Corporation', 'Co-Owner', 'Individual', 'Partnership', 'Foreign Corporation']
          - name: status
            tests:
            - accepted_values:
                values: ['Valid', 'Registered to Mfr']
      - name: flights_2008
        desciption: Table contains details of flights recorded in 2008, i.e. schedule, delay, distance, flight_number, etc.
        columns:
          - name: year
            tests:
            - accepted_values:
                values: [2008]
          - name: month
            description: Numeric representation of the month.
          - name: day_of_month
            description: Numeric representation of the day within a month.
          - name: day_of_week
            description: Numeric representation of the day of the week.
          - name: dep_time
            description: Actual departure time.
          - name: crs_dep_time
            description: Scheduled departure time.
          - name: arr_time
            description: Actual arrival time.
          - name: crs_arr_time
            description: Scheduled arrival time.
          - name: unique_carrier
            description: Code or name representing the unique airline carrier.
          - name: flightnum
            description: Flight number assigned by the airline.
          - name: tailnum
            description: Tail number or registration number of the aircraft.
          - name: actual_elapsed_time
            description: Actual elapsed time of the flight.
          - name: crs_elapsed_time
            description: Scheduled elapsed time of the flight.
          - name: air_time
            description: Duration of the flight in the air.
          - name: arr_delay
            description: Arrival delay in minutes.
          - name: dep_delay
            description: Departure delay in minutes.  
          - name: origin
            description: Code or name representing the origin airport.
            data_type: string
            constraints:
              - type: not_null
          - name: dest
            description: Code or name representing the destination airport.
            data_type: string
            constraints:
              - type: not_null
          - name: distance
            description: Distance of the flight route.
          - name: taxi_in
            description: Taxi-in time at the destination airport.
          - name: taxi_out
            description: Taxi-out time at the origin airport.
          - name: cancelled
            description: Indicates if the flight was cancelled (0 = not cancelled, 1 = cancelled).
          - name: cancellation_code
            description: Code representing the reason for cancellation.
          - name: diverted
            description: Indicates if the flight was diverted (0 = not diverted, 1 = diverted).
          - name: carrier_delay
            description: Delay caused by the carrier.
          - name: weather_delay
            description: Delay caused by weather conditions.
          - name: os_delay
            description: Delay attributed to the National Airspace System.
          - name: security_delay
            description: Delay caused by security issues.
          - name: late_aircraft_delay